concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "local-runner"
  url = "http://host.docker.internal:8929"
  id = 1
  token = "glrtr--NDitM7YBA0fNn4_xQjlsG86MQpwOjEKdDozCw.01.121u94ges"
  token_obtained_at = 2025-09-09T13:49:12Z
  token_expires_at = 0001-01-01T00:00:00Z
  clone_url = "http://host.docker.internal:8929"
  executor = "docker"
  [runners.docker]
    image = "alpine:3.20"
    pull_policy = "if-not-present"
    privileged = false
    shm_size = 0
    tls_verify = false